In [418]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sampleGenerator import LHSampler, SampleGenerator
from itertools import product

In [419]:
def round_linear(x, base=.05):
  return (base * (np.array(x) / base).round())

def round_log(x, base=10):
  return (base ** ((np.log10(np.array(x))/np.log10(base)).round()))

def round_list(x, lst):
  arr = np.array(x)
  out = np.zeros(arr.shape)
  for i in range(len(arr)):
    out[i] = min(lst, key=lambda y: abs(y - arr[i]))
  return out

First phase parameters

In [420]:
type_1st_phase = {"m": 1.75, "s": 1.25, "dist": "uniform", "round": round_linear, "base": 1}
s1 = {"m": 200, "s": 100, "dist": "uniform", "round": round_linear, "base": 20}
v1 = {"m": 0.3, "s": 0.2, "dist": "uniform", "round": round_linear, "base": 0.1}
s2_s1 = {"m": 200, "s": 100, "dist": "uniform", "round": round_linear, "base": 20}  # s2 - s1
v2_v1 = {"m": 2, "s": 1, "dist": "uniform", "round": round_linear, "base": 1/3}     # v2/v1
vcrit = {"m": 0.65, "s": 0.35, "dist": "uniform", "round": round_linear, "base": 0.1}   # ratio to v_crit

Second phase parameters

In [421]:
vI = {"m": 3, "s": 1, "dist": "uniform", "round": round_linear, "base": 0.5}
s3_shift = {"m": 25, "s": 75, "dist": "uniform", "round": round_linear, "base": 20}     # shift to s_ma
v3_vI_v2 = {"m": 0.5, "s": 0.5, "dist": "uniform", "round": round_linear, "base": 0.1}  # ratio of v3/(vI-v2) --> 1 => vI, 0 => v2
s34_shift = {"m": 70, "s": 30, "dist": "uniform", "round": round_linear, "base": 20}    # s4 - s3
sbreak_shift = {"m": -35, "s": 15, "dist": "uniform", "round": round_linear, "base": 10}    # shift to s_brake
vbrake = {"m": 1, "s": 0.5, "dist": "uniform", "round": round_linear, "base": 0.25}

Third phase parameters

In [422]:
p0 = {"m": 300, "s": 150, "dist": "uniform", "round": round_linear, "base": 100}
dp1 = {"m": 100, "s": 150, "dist": "uniform", "round": round_linear, "base": 100}
t1 = {"m": 0.065, "s": 0.035, "dist": "uniform", "round": round_linear, "base": 0.01}
dp2 = {"m": 150, "s": 200, "dist": "uniform", "round": round_linear, "base": 100}
dt2 = {"m": 0.06, "s": 0.04, "dist": "uniform", "round": round_linear, "base": 0.02}
sol_time = {"m": 11, "s": 9, "dist": "uniform", "round": round_log, "base": 2}

Temperatures

In [423]:
hm2 = {"m": 180, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
hm3 = {"m": 160, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
hm4 = {"m": 160, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
m4 = {"m": 120, "s": 25, "dist": "normal", "round": round_linear, "base": 20}

piston = {"m": 60, "s": 25, "dist": "normal", "round": round_linear, "base": 20}

hf1 = {"m": 160, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
hf2 = {"m": 180, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
hf3 = {"m": 160, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
f3 = {"m": 120, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
f4 = {"m": 120, "s": 25, "dist": "normal", "round": round_linear, "base": 20}

metal = {"m": 690, "s": 20, "dist": "normal", "round": round_linear, "base": 20}

Vacuum

In [424]:
pvac = {"m": 6.5, "s": 4, "dist": "uniform", "round": round_list, "base": [10, 20, 50, 100, 200, 500, 1000]}

Sampling

In [425]:
params = {
    "type_1st_phase": type_1st_phase,
    "s1": s1,
    "v1": v1,
    "s2_s1": s2_s1,
    "v2_v1": v2_v1,
    "vcrit": vcrit,
    "vI": vI,
    "s3_shift": s3_shift,
    "v3_vI_v2": v3_vI_v2,
    "s34_shift": s34_shift,
    "sbreak_shift": sbreak_shift,
    "vbrake": vbrake,
    "p0": p0,
    "dp1": dp1,
    "t1": t1,
    "dp2": dp2,
    "dt2": dt2,
    "sol_time": sol_time,
    "hm2": hm2,
    "hm3": hm3,
    "hm4": hm4,
    "m4": m4,
    "piston": piston,
    "hf1": hf1,
    "hf2": hf2,
    "hf3": hf3,
    "f3": f3,
    "f4": f4,
    "metal": metal,
    "pvac": pvac
}

In [426]:
n_samples = 100
samples = SampleGenerator(LHSampler())(n_samples, [p["m"] for p in params.values()], [p["s"] for p in params.values()], [p["dist"] for p in params.values()])
samples

array([[1.17756857e+00, 2.59837910e+02, 4.05037101e-01, ...,
        9.36489251e+01, 6.70556724e+02, 3.98463592e+00],
       [1.89728564e+00, 2.21684049e+02, 3.83255754e-01, ...,
        1.35093505e+02, 6.64601647e+02, 5.76782129e+00],
       [1.34637514e+00, 1.55905028e+02, 2.63795813e-01, ...,
        1.34187757e+02, 7.31396124e+02, 9.37882185e+00],
       ...,
       [1.43916708e+00, 2.47707846e+02, 3.01260006e-01, ...,
        1.03538137e+02, 6.97481200e+02, 4.92460722e+00],
       [5.92827324e-01, 2.00137134e+02, 3.84507720e-01, ...,
        1.31405174e+02, 6.59228698e+02, 9.68618885e+00],
       [1.97735014e+00, 2.10160333e+02, 1.38136345e-01, ...,
        1.78675114e+02, 6.88060568e+02, 5.12909324e+00]])

Discretize the values

In [427]:
rounded_samples = np.zeros(samples.shape)
for i, p in enumerate(params.values()):
  rounded_samples[:, i] = p["round"](samples[:, i], p["base"]) if p != pvac else p["round"](2**samples[:, i], p["base"])
rounded_samples

array([[1.0e+00, 2.6e+02, 4.0e-01, ..., 1.0e+02, 6.8e+02, 2.0e+01],
       [2.0e+00, 2.2e+02, 4.0e-01, ..., 1.4e+02, 6.6e+02, 5.0e+01],
       [1.0e+00, 1.6e+02, 3.0e-01, ..., 1.4e+02, 7.4e+02, 5.0e+02],
       ...,
       [1.0e+00, 2.4e+02, 3.0e-01, ..., 1.0e+02, 7.0e+02, 2.0e+01],
       [1.0e+00, 2.0e+02, 4.0e-01, ..., 1.4e+02, 6.6e+02, 1.0e+03],
       [2.0e+00, 2.2e+02, 1.0e-01, ..., 1.8e+02, 6.8e+02, 2.0e+01]])

In [428]:
samples_df = pd.DataFrame(rounded_samples, columns=params.keys())
samples_df.head()

,type_1st_phase,s1,v1,s2_s1,v2_v1,vcrit,vI,s3_shift,v3_vI_v2,s34_shift,...,hm4,m4,piston,hf1,hf2,hf3,f3,f4,metal,pvac
0,1.0,260.0,0.4,260.0,1.333333,0.4,3.0,-20.0,0.8,40.0,...,140.0,120.0,40.0,180.0,200.0,160.0,100.0,100.0,680.0,20.0
1,2.0,220.0,0.4,280.0,2.666667,0.9,4.0,60.0,0.4,80.0,...,120.0,60.0,100.0,160.0,160.0,140.0,120.0,140.0,660.0,50.0
2,1.0,160.0,0.3,260.0,1.333333,0.5,3.5,60.0,0.7,60.0,...,160.0,100.0,60.0,160.0,180.0,200.0,180.0,140.0,740.0,500.0
3,2.0,140.0,0.2,140.0,1.333333,0.7,2.5,40.0,0.3,80.0,...,180.0,120.0,40.0,140.0,240.0,160.0,100.0,80.0,680.0,200.0
4,3.0,100.0,0.5,300.0,1.666667,0.8,3.5,-40.0,0.3,80.0,...,180.0,160.0,-0.0,160.0,180.0,160.0,120.0,120.0,640.0,100.0

In [429]:
samples_df.describe()

,type_1st_phase,s1,v1,s2_s1,v2_v1,vcrit,vI,s3_shift,v3_vI_v2,s34_shift,...,hm4,m4,piston,hf1,hf2,hf3,f3,f4,metal,pvac
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.00000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,1.800000,200.000000,0.301000,200.000000,2.000000,0.648000,2.995000,25.200000,0.500000,70.000000,...,160.000000,120.20000,59.60000,159.400000,180.000000,159.800000,120.000000,119.600000,690.000000,241.300000
std,0.752101,58.603272,0.124312,58.603272,0.593644,0.206696,0.617485,43.449262,0.293016,18.963016,...,25.898013,26.13021,25.26306,26.431539,25.105837,25.975124,26.053558,25.580927,20.597146,321.576467
min,1.000000,100.000000,0.100000,100.000000,1.000000,0.300000,2.000000,-40.000000,0.000000,40.000000,...,100.000000,60.00000,0.00000,80.000000,120.000000,80.000000,60.000000,60.000000,640.000000,10.000000
25%,1.000000,155.000000,0.200000,155.000000,1.583333,0.500000,2.500000,-20.000000,0.275000,60.000000,...,140.000000,100.00000,40.00000,140.000000,160.000000,140.000000,100.000000,100.000000,680.000000,20.000000
50%,2.000000,200.000000,0.300000,200.000000,2.000000,0.650000,3.000000,20.000000,0.500000,70.000000,...,160.000000,120.00000,60.00000,160.000000,180.000000,160.000000,120.000000,120.000000,690.000000,100.000000
75%,2.000000,245.000000,0.400000,245.000000,2.416667,0.800000,3.500000,60.000000,0.725000,80.000000,...,180.000000,140.00000,80.00000,180.000000,200.000000,180.000000,140.000000,140.000000,700.000000,275.000000
max,3.000000,300.000000,0.500000,300.000000,3.000000,1.000000,4.000000,100.000000,1.000000,100.000000,...,240.000000,200.00000,120.00000,220.000000,240.000000,220.000000,200.000000,180.000000,740.000000,1000.000000

Adjust parameters s.t. they can be used directly

In [430]:
samples_df.rename(columns={"s2_s1": "s2", "v2_v1": "v2", "v3_vI_v2": "v3", "dp1": "p1", "dp2": "p2", "dt2": "t2"}, inplace=True)
samples_df["s2"] += samples_df["s1"]
samples_df["v2"] *= samples_df["v1"]
samples_df["v2"] = samples_df["v2"].round(1)
samples_df["v3"] = samples_df["v3"]*(samples_df["vI"] - samples_df["v2"]) + samples_df["v2"]
samples_df["v3"] = samples_df["v3"].round(1)
samples_df["p1"] += samples_df["p0"]
samples_df["p2"] += samples_df["p1"]
samples_df["t2"] += samples_df["t1"]
samples_df.replace({"type_1st_phase": {1: "no optimization", 2: "Buehler any", 3: "Nogowizin"}}, inplace=True)
samples_df

,type_1st_phase,s1,v1,s2,v2,vcrit,vI,s3_shift,v3,s34_shift,...,hm4,m4,piston,hf1,hf2,hf3,f3,f4,metal,pvac
0,no optimization,260.0,0.4,520.0,0.5,0.4,3.0,-20.0,2.5,40.0,...,140.0,120.0,40.0,180.0,200.0,160.0,100.0,100.0,680.0,20.0
1,Buehler any,220.0,0.4,500.0,1.1,0.9,4.0,60.0,2.3,80.0,...,120.0,60.0,100.0,160.0,160.0,140.0,120.0,140.0,660.0,50.0
2,no optimization,160.0,0.3,420.0,0.4,0.5,3.5,60.0,2.6,60.0,...,160.0,100.0,60.0,160.0,180.0,200.0,180.0,140.0,740.0,500.0
3,Buehler any,140.0,0.2,280.0,0.3,0.7,2.5,40.0,1.0,80.0,...,180.0,120.0,40.0,140.0,240.0,160.0,100.0,80.0,680.0,200.0
4,Nogowizin,100.0,0.5,400.0,0.8,0.8,3.5,-40.0,1.6,80.0,...,180.0,160.0,-0.0,160.0,180.0,160.0,120.0,120.0,640.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,no optimization,140.0,0.2,240.0,0.5,1.0,3.0,-20.0,0.8,60.0,...,200.0,120.0,80.0,140.0,160.0,140.0,140.0,120.0,680.0,10.0
96,Buehler any,260.0,0.1,500.0,0.2,0.6,4.0,20.0,2.9,100.0,...,180.0,100.0,60.0,140.0,160.0,140.0,100.0,80.0,700.0,500.0
97,no optimization,240.0,0.3,420.0,0.6,0.4,3.0,40.0,2.5,60.0,...,160.0,120.0,60.0,160.0,240.0,140.0,80.0,100.0,700.0,20.0
98,no optimization,200.0,0.4,380.0,0.5,0.3,3.5,20.0,3.5,60.0,...,100.0,120.0,40.0,180.0,160.0,180.0,160.0,140.0,660.0,1000.0
99,Buehler any,220.0,0.1,440.0,0.3,0.8,3.5,-20.0,0.9,80.0,...,200.0,80.0,60.0,140.0,180.0,180.0,120.0,180.0,680.0,20.0

Clip temperatures

In [431]:
samples_df["hm2"] = samples_df["hm2"].clip(hm2["m"]-40, hm2["m"]+40)
samples_df["hm3"] = samples_df["hm3"].clip(hm3["m"]-40, hm3["m"]+40)
samples_df["hm4"] = samples_df["hm4"].clip(hm4["m"]-40, hm4["m"]+40)
samples_df["m4"] = samples_df["m4"].clip(m4["m"]-40, m4["m"]+40)

samples_df["piston"] = samples_df["piston"].clip(piston["m"]-40, piston["m"]+40)

samples_df["hf1"] = samples_df["hf1"].clip(hf1["m"]-40, hf1["m"]+40)
samples_df["hf2"] = samples_df["hf2"].clip(hf2["m"]-40, hf2["m"]+40)
samples_df["hf3"] = samples_df["hf3"].clip(hf3["m"]-40, hf3["m"]+40)
samples_df["f3"] = samples_df["f3"].clip(f3["m"]-40, f3["m"]+40)
samples_df["f4"] = samples_df["f4"].clip(f4["m"]-40, f4["m"]+40)

samples_df["metal"] = samples_df["metal"].clip(metal["m"]-30, metal["m"]+30)

In [432]:
samples_df.describe()

,s1,v1,s2,v2,vcrit,vI,s3_shift,v3,s34_shift,sbreak_shift,...,hm4,m4,piston,hf1,hf2,hf3,f3,f4,metal,pvac
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,200.000000,0.301000,400.000000,0.599000,0.648000,2.995000,25.200000,1.800000,70.000000,-35.100000,...,160.000000,120.200000,59.60000,159.800000,180.000000,160.200000,119.800000,119.800000,690.000000,241.300000
std,58.603272,0.124312,87.015615,0.313499,0.206696,0.617485,43.449262,0.792006,18.963016,9.586923,...,23.268308,23.526473,23.60962,23.867479,23.441309,23.354103,23.867479,23.526473,18.963016,321.576467
min,100.000000,0.100000,220.000000,0.100000,0.300000,2.000000,-40.000000,0.500000,40.000000,-50.000000,...,120.000000,80.000000,20.00000,120.000000,140.000000,120.000000,80.000000,80.000000,660.000000,10.000000
25%,155.000000,0.200000,340.000000,0.400000,0.500000,2.500000,-20.000000,1.175000,60.000000,-40.000000,...,140.000000,100.000000,40.00000,140.000000,160.000000,140.000000,100.000000,100.000000,680.000000,20.000000
50%,200.000000,0.300000,400.000000,0.500000,0.650000,3.000000,20.000000,1.800000,70.000000,-35.000000,...,160.000000,120.000000,60.00000,160.000000,180.000000,160.000000,120.000000,120.000000,690.000000,100.000000
75%,245.000000,0.400000,460.000000,0.800000,0.800000,3.500000,60.000000,2.300000,80.000000,-30.000000,...,180.000000,140.000000,80.00000,180.000000,200.000000,180.000000,140.000000,140.000000,700.000000,275.000000
max,300.000000,0.500000,600.000000,1.500000,1.000000,4.000000,100.000000,3.700000,100.000000,-20.000000,...,200.000000,160.000000,100.00000,200.000000,220.000000,200.000000,160.000000,160.000000,720.000000,1000.000000

Shot curve generation

In [433]:
# please check - just took the values from the Excel
d_M = 80/1000
V_I = 1527/1e6
V_part = 1025/1e6
V_A = 1120 / 1e6
V_channel = 407/1e6
t_biscuit = 27/1000
l_m_activ = 756/1000
H_biscuit = 30/1000
f_liq_sol = 0.9425

fraction_prefilling = 0

In [434]:
A_dM = np.square(d_M)*np.pi/4
FR = V_I/(A_dM*l_m_activ)
V_biscuit = A_dM*t_biscuit

V_prefilling = fraction_prefilling * V_part

s_m_100 = l_m_activ*(1-FR)
s_ma = s_m_100 + (V_channel-V_biscuit)/A_dM
s_pf = s_m_100 + (V_channel-V_biscuit+V_prefilling)/A_dM
s_ov = s_m_100 + (V_channel-V_biscuit+V_part)/A_dM
s_ffin = s_m_100 + (V_channel - V_biscuit + V_A)/A_dM

s_Ifin_solid = s_ffin + V_I * (1-f_liq_sol)/A_dM

v_kr=(9.81*d_M)**0.5*(1.386-1.915*FR+0.616*FR**2) 

# unit to mm
s_m_100 *= 1000
s_ma *= 1000
s_pf *= 1000
s_ov *= 1000
s_ffin *= 1000
s_Ifin_solid *= 1000

In [435]:
samples_df.rename(columns={"s3_shift": "s3", "s34_shift": "s4", "sbreak_shift": "s_start_braking"}, inplace=True)
samples_df["s3"] += s_ma
samples_df["s4"] += samples_df["s3"]
samples_df["s_start_braking"] += s_ffin
samples_df["vcrit"] *= v_kr
samples_df = samples_df.round(4)
samples_df.head()

,type_1st_phase,s1,v1,s2,v2,vcrit,vI,s3,v3,s4,...,hm4,m4,piston,hf1,hf2,hf3,f3,f4,metal,pvac
0,no optimization,260.0,0.4,520.0,0.5,0.2537,3.0,486.1831,2.5,526.1831,...,140.0,120.0,40.0,180.0,200.0,160.0,100.0,100.0,680.0,20.0
1,Buehler any,220.0,0.4,500.0,1.1,0.5708,4.0,566.1831,2.3,646.1831,...,120.0,80.0,100.0,160.0,160.0,140.0,120.0,140.0,660.0,50.0
2,no optimization,160.0,0.3,420.0,0.4,0.3171,3.5,566.1831,2.6,626.1831,...,160.0,100.0,60.0,160.0,180.0,200.0,160.0,140.0,720.0,500.0
3,Buehler any,140.0,0.2,280.0,0.3,0.4440,2.5,546.1831,1.0,626.1831,...,180.0,120.0,40.0,140.0,220.0,160.0,100.0,80.0,680.0,200.0
4,Nogowizin,100.0,0.5,400.0,0.8,0.5074,3.5,466.1831,1.6,546.1831,...,180.0,160.0,20.0,160.0,180.0,160.0,120.0,120.0,660.0,100.0

Save to csv

In [436]:
samples_df.to_csv("Parameter_combinations_202509.csv")

Alternative: Vary mold temperatures uniformly (all temperatures for BS/FS are adjusted the same) to reduce temperature changes.

In [437]:
samples_df["hf2"] = samples_df["hf1"] + hf2["m"] - hf1["m"]
samples_df["hf3"] = samples_df["hf1"] + hf3["m"] - hf1["m"]
samples_df["f3"] = samples_df["hf1"] + f3["m"] - hf1["m"]
samples_df["f4"] = samples_df["hf1"] + f4["m"] - hf1["m"]

samples_df["hm3"] = samples_df["hm2"] + hm3["m"] - hm2["m"]
samples_df["hm4"] = samples_df["hm2"] + hm4["m"] - hm2["m"]
samples_df["m4"] = samples_df["hm2"] + m4["m"] - hm2["m"]
samples_df.head()

,type_1st_phase,s1,v1,s2,v2,vcrit,vI,s3,v3,s4,...,hm4,m4,piston,hf1,hf2,hf3,f3,f4,metal,pvac
0,no optimization,260.0,0.4,520.0,0.5,0.2537,3.0,486.1831,2.5,526.1831,...,160.0,120.0,40.0,180.0,200.0,180.0,140.0,140.0,680.0,20.0
1,Buehler any,220.0,0.4,500.0,1.1,0.5708,4.0,566.1831,2.3,646.1831,...,140.0,100.0,100.0,160.0,180.0,160.0,120.0,120.0,660.0,50.0
2,no optimization,160.0,0.3,420.0,0.4,0.3171,3.5,566.1831,2.6,626.1831,...,180.0,140.0,60.0,160.0,180.0,160.0,120.0,120.0,720.0,500.0
3,Buehler any,140.0,0.2,280.0,0.3,0.4440,2.5,546.1831,1.0,626.1831,...,160.0,120.0,40.0,140.0,160.0,140.0,100.0,100.0,680.0,200.0
4,Nogowizin,100.0,0.5,400.0,0.8,0.5074,3.5,466.1831,1.6,546.1831,...,140.0,100.0,20.0,160.0,180.0,160.0,120.0,120.0,660.0,100.0

Save to csv

In [438]:
samples_df.to_csv("Parameter_combinations_uniform_mold_changes_202509.csv")

Alternative: Reduce number of levels to 3 (0, $\pm$ 30K) for mold and metal temperatures and keep piston constant.

In [439]:
hm2 = {"m": 180, "s": 30, "dist": "uniform", "round": round_linear, "base": 30}
hm3 = {"m": 160, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
hm4 = {"m": 160, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
m4 = {"m": 120, "s": 25, "dist": "normal", "round": round_linear, "base": 20}

piston = {"m": 60, "s": 25, "dist": "normal", "round": round_linear, "base": 20}

hf1 = {"m": 160, "s": 30, "dist": "uniform", "round": round_linear, "base": 30}
hf2 = {"m": 180, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
hf3 = {"m": 160, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
f3 = {"m": 120, "s": 25, "dist": "normal", "round": round_linear, "base": 20}
f4 = {"m": 120, "s": 25, "dist": "normal", "round": round_linear, "base": 20}

metal = {"m": 700, "s": 20, "dist": "uniform", "round": round_linear, "base": 20}

In [440]:
params = {
    "type_1st_phase": type_1st_phase,
    "s1": s1,
    "v1": v1,
    "s2_s1": s2_s1,
    "v2_v1": v2_v1,
    "vcrit": vcrit,
    "vI": vI,
    "s3_shift": s3_shift,
    "v3_vI_v2": v3_vI_v2,
    "s34_shift": s34_shift,
    "sbreak_shift": sbreak_shift,
    "vbrake": vbrake,
    "p0": p0,
    "dp1": dp1,
    "t1": t1,
    "dp2": dp2,
    "dt2": dt2,
    "sol_time": sol_time,
    "pvac": pvac
}

In [441]:
n_samples = 15*27
samples = SampleGenerator(LHSampler())(n_samples, [p["m"] for p in params.values()], [p["s"] for p in params.values()], [p["dist"] for p in params.values()])
samples

array([[2.54037021e+00, 1.86944744e+02, 4.75133731e-01, ...,
        4.27997044e-02, 1.36402505e+01, 1.02314172e+01],
       [1.38498863e+00, 2.71038850e+02, 1.15802136e-01, ...,
        2.44904183e-02, 1.37251295e+01, 2.69473998e+00],
       [2.05123785e+00, 2.12623870e+02, 1.29719012e-01, ...,
        7.66477633e-02, 1.93670651e+01, 4.19846288e+00],
       ...,
       [2.88130689e+00, 1.95976606e+02, 1.61031297e-01, ...,
        8.77423069e-02, 5.59167510e+00, 5.81485498e+00],
       [1.87681882e+00, 1.82425362e+02, 1.12318119e-01, ...,
        7.98028885e-02, 3.08472913e+00, 9.37351697e+00],
       [2.42298360e+00, 1.06116053e+02, 1.96103043e-01, ...,
        2.97096047e-02, 1.04316365e+01, 9.18754928e+00]])

In [442]:
rounded_samples = np.zeros(samples.shape)
for i, p in enumerate(params.values()):
  rounded_samples[:, i] = p["round"](samples[:, i], p["base"]) if p != pvac else p["round"](2**samples[:, i], p["base"])
rounded_samples

array([[3.0e+00, 1.8e+02, 5.0e-01, ..., 4.0e-02, 1.6e+01, 1.0e+03],
       [1.0e+00, 2.8e+02, 1.0e-01, ..., 2.0e-02, 1.6e+01, 1.0e+01],
       [2.0e+00, 2.2e+02, 1.0e-01, ..., 8.0e-02, 1.6e+01, 2.0e+01],
       ...,
       [3.0e+00, 2.0e+02, 2.0e-01, ..., 8.0e-02, 4.0e+00, 5.0e+01],
       [2.0e+00, 1.8e+02, 1.0e-01, ..., 8.0e-02, 4.0e+00, 5.0e+02],
       [2.0e+00, 1.0e+02, 2.0e-01, ..., 2.0e-02, 8.0e+00, 5.0e+02]])

In [443]:
samples_df = pd.DataFrame(rounded_samples, columns=params.keys())
samples_df.head()

,type_1st_phase,s1,v1,s2_s1,v2_v1,vcrit,vI,s3_shift,v3_vI_v2,s34_shift,sbreak_shift,vbrake,p0,dp1,t1,dp2,dt2,sol_time,pvac
0,3.0,180.0,0.5,280.0,1.666667,0.5,2.0,20.0,0.8,60.0,-30.0,0.75,300.0,0.0,0.06,-0.0,0.04,16.0,1000.0
1,1.0,280.0,0.1,140.0,1.333333,0.6,2.5,60.0,0.1,100.0,-50.0,1.25,400.0,0.0,0.07,-0.0,0.02,16.0,10.0
2,2.0,220.0,0.1,300.0,2.333333,0.7,2.0,-20.0,0.8,80.0,-50.0,1.25,300.0,200.0,0.08,100.0,0.08,16.0,20.0
3,1.0,140.0,0.4,160.0,2.000000,0.8,2.5,-20.0,0.7,40.0,-50.0,0.75,200.0,0.0,0.05,100.0,0.06,8.0,200.0
4,1.0,120.0,0.4,160.0,2.333333,0.9,4.0,20.0,0.4,60.0,-20.0,1.00,200.0,-0.0,0.05,200.0,0.08,4.0,50.0

In [444]:
samples_df.rename(columns={"s2_s1": "s2", "v2_v1": "v2", "v3_vI_v2": "v3", "dp1": "p1", "dp2": "p2", "dt2": "t2"}, inplace=True)
samples_df["s2"] += samples_df["s1"]
samples_df["v2"] *= samples_df["v1"]
samples_df["v2"] = samples_df["v2"].round(1)
samples_df["v3"] = samples_df["v3"]*(samples_df["vI"] - samples_df["v2"]) + samples_df["v2"]
samples_df["v3"] = samples_df["v3"].round(1)
samples_df["p1"] += samples_df["p0"]
samples_df["p2"] += samples_df["p1"]
samples_df["t2"] += samples_df["t1"]
samples_df.replace({"type_1st_phase": {1: "no optimization", 2: "Buehler any", 3: "Nogowizin"}}, inplace=True)
samples_df

,type_1st_phase,s1,v1,s2,v2,vcrit,vI,s3_shift,v3,s34_shift,sbreak_shift,vbrake,p0,p1,t1,p2,t2,sol_time,pvac
0,Nogowizin,180.0,0.5,460.0,0.8,0.5,2.0,20.0,1.8,60.0,-30.0,0.75,300.0,300.0,0.06,300.0,0.10,16.0,1000.0
1,no optimization,280.0,0.1,420.0,0.1,0.6,2.5,60.0,0.3,100.0,-50.0,1.25,400.0,400.0,0.07,400.0,0.09,16.0,10.0
2,Buehler any,220.0,0.1,520.0,0.2,0.7,2.0,-20.0,1.6,80.0,-50.0,1.25,300.0,500.0,0.08,600.0,0.16,16.0,20.0
3,no optimization,140.0,0.4,300.0,0.8,0.8,2.5,-20.0,2.0,40.0,-50.0,0.75,200.0,200.0,0.05,300.0,0.11,8.0,200.0
4,no optimization,120.0,0.4,280.0,0.9,0.9,4.0,20.0,2.1,60.0,-20.0,1.00,200.0,200.0,0.05,400.0,0.13,4.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,Buehler any,300.0,0.2,460.0,0.3,0.5,2.5,60.0,2.5,80.0,-30.0,1.00,300.0,400.0,0.08,600.0,0.16,16.0,20.0
401,Buehler any,220.0,0.5,500.0,0.5,0.9,2.5,0.0,1.9,80.0,-40.0,1.25,300.0,400.0,0.08,700.0,0.12,4.0,20.0
402,Nogowizin,200.0,0.2,360.0,0.3,0.4,2.5,20.0,1.8,100.0,-30.0,1.25,400.0,600.0,0.06,700.0,0.14,4.0,50.0
403,Buehler any,180.0,0.1,300.0,0.2,0.7,3.5,100.0,0.9,60.0,-40.0,0.75,400.0,400.0,0.08,500.0,0.16,4.0,500.0
404,Buehler any,100.0,0.2,380.0,0.5,0.4,2.5,0.0,2.5,60.0,-30.0,0.75,200.0,400.0,0.07,700.0,0.09,8.0,500.0

In [445]:
samples_df.rename(columns={"s3_shift": "s3", "s34_shift": "s4", "sbreak_shift": "s_start_braking"}, inplace=True)
samples_df["s3"] += s_ma
samples_df["s4"] += samples_df["s3"]
samples_df["s_start_braking"] += s_ffin
samples_df["vcrit"] *= v_kr
samples_df = samples_df.round(4)
samples_df.head()

,type_1st_phase,s1,v1,s2,v2,vcrit,vI,s3,v3,s4,s_start_braking,vbrake,p0,p1,t1,p2,t2,sol_time,pvac
0,Nogowizin,180.0,0.5,460.0,0.8,0.3171,2.0,526.1831,1.8,586.1831,699.0,0.75,300.0,300.0,0.06,300.0,0.10,16.0,1000.0
1,no optimization,280.0,0.1,420.0,0.1,0.3806,2.5,566.1831,0.3,666.1831,679.0,1.25,400.0,400.0,0.07,400.0,0.09,16.0,10.0
2,Buehler any,220.0,0.1,520.0,0.2,0.4440,2.0,486.1831,1.6,566.1831,679.0,1.25,300.0,500.0,0.08,600.0,0.16,16.0,20.0
3,no optimization,140.0,0.4,300.0,0.8,0.5074,2.5,486.1831,2.0,526.1831,679.0,0.75,200.0,200.0,0.05,300.0,0.11,8.0,200.0
4,no optimization,120.0,0.4,280.0,0.9,0.5708,4.0,526.1831,2.1,586.1831,709.0,1.00,200.0,200.0,0.05,400.0,0.13,4.0,50.0

In [446]:
temp_settings = np.array(list(product([680,700,720],[130,160,190],[150,180,210])))
np.random.default_rng().shuffle(temp_settings)

In [447]:
samples_df["hf1"] = np.outer(temp_settings[:,1], np.ones(15)).ravel()
samples_df["hm2"] = np.outer(temp_settings[:,2], np.ones(15)).ravel()
samples_df["metal"] = np.outer(temp_settings[:,0], np.ones(15)).ravel()

In [448]:
samples_df["hf2"] = samples_df["hf1"] + hf2["m"] - hf1["m"]
samples_df["hf3"] = samples_df["hf1"] + hf3["m"] - hf1["m"]
samples_df["f3"] = samples_df["hf1"] + f3["m"] - hf1["m"]
samples_df["f4"] = samples_df["hf1"] + f4["m"] - hf1["m"]

samples_df["hm3"] = samples_df["hm2"] + hm3["m"] - hm2["m"]
samples_df["hm4"] = samples_df["hm2"] + hm4["m"] - hm2["m"]
samples_df["m4"] = samples_df["hm2"] + m4["m"] - hm2["m"]

samples_df["piston"] = 60
samples_df.head()

,type_1st_phase,s1,v1,s2,v2,vcrit,vI,s3,v3,s4,...,hm2,metal,hf2,hf3,f3,f4,hm3,hm4,m4,piston
0,Nogowizin,180.0,0.5,460.0,0.8,0.3171,2.0,526.1831,1.8,586.1831,...,180.0,680.0,150.0,130.0,90.0,90.0,160.0,160.0,120.0,60
1,no optimization,280.0,0.1,420.0,0.1,0.3806,2.5,566.1831,0.3,666.1831,...,180.0,680.0,150.0,130.0,90.0,90.0,160.0,160.0,120.0,60
2,Buehler any,220.0,0.1,520.0,0.2,0.4440,2.0,486.1831,1.6,566.1831,...,180.0,680.0,150.0,130.0,90.0,90.0,160.0,160.0,120.0,60
3,no optimization,140.0,0.4,300.0,0.8,0.5074,2.5,486.1831,2.0,526.1831,...,180.0,680.0,150.0,130.0,90.0,90.0,160.0,160.0,120.0,60
4,no optimization,120.0,0.4,280.0,0.9,0.5708,4.0,526.1831,2.1,586.1831,...,180.0,680.0,150.0,130.0,90.0,90.0,160.0,160.0,120.0,60

In [449]:
samples_df.to_csv("Parameter_combinations_uniform_mold_changes_202509.csv")